### PR TITLE
Potential fixes for poll problems

### LINKED ISSUE #52: !poll multi does not show title
!poll multi is supposed to support having a poll title, but that isn't shown currently!

### LINKED ISSUE #53: Mentions don't show in polls
Channels and user mentions don't show in poll, as the description is put in the title. I believe descriptions were added into a field when we had trup.

image

### PR DESCRIPTION
**Pull request by JavaCafe01**
This should fix #52 and fix #53. This is literally my first attempt at writing Rust code, I would love for some feedback lol.

### CODE REVIEW

**Comment by elkowar** [comment]
review:
image

File: src/extensions.rs [hunk 1]
```diff
@@ -195,4 +195,27 @@ impl<T: AsRef<str>> T {
         let index = s.find(c)?;
         Some((&s[..index], &s[index + c.len_utf8()..]))
     }
+
+    fn split_at_word<'a>(&'a self, split_at: &str) -> (String, String) {
+        let str: &str = self.as_ref();
+        let mut result = (String::from(""), String::from(""));
```
Comment (elkowar) [inline src/extensions.rs:201]: No need to have this be mutable, you can just easily return the tuples directly from the code. Also, String::new() exists as a shorter version of String::from("")

File: src/extensions.rs [hunk 2]
```diff
@@ -195,4 +195,27 @@ impl<T: AsRef<str>> T {
...
+        let mut splits = str.trim().split(' ').collect_vec();
+        match splits.last() {
```
Comment (elkowar) [inline src/extensions.rs:203]: Does this need special handling? not really, no? I'd think that just sth like 
```
let mut words = self.as_ref().trim().split(' ').collect_vec();
match words.iter().position(|word| w == &split_at) {
  Some(word_idx) => {
    let right_side = words.split_off(word_idx + 1).join(" ");
    (words.join(" "), right_side)
  }
  None => (self.to_string(), String::new())
}
```
should do the trick, no?

File: src/extensions.rs [hunk 3]
```diff
@@ -195,4 +195,27 @@ impl<T: AsRef<str>> T {
...
+            Some(word) => {
+                println!("\nLast Word: {}\n", word);
+                if word.clone() != split_at {
+                    result.1 = splits
+                        .split_off(splits.iter().position(|&i| i == split_at).unwrap() + 1)
+                        .join(" ");
+                    println!("\nDescription: {}\n", result.1);
```
Comment (elkowar) [inline src/extensions.rs]: remove ur debug stuff uwu

File: src/commands/poll.rs [hunk 4]
```diff
@@ -40,7 +41,10 @@ pub async fn poll(ctx: &client::Context, msg: &Message, args: Args) -> CommandRe
 #[usage("poll multi [title] <one option per line>")]
 async fn poll_multi(ctx: &client::Context, msg: &Message) -> CommandResult {
     let lines = msg.content.lines().collect_vec();
-    let title = lines.first();
+    let title = lines
+        .first()
+        .map(|line| line.split_at_word("multi").1)
+        .unwrap();
     let mut lines = lines.clone();
```
[the remark this answers is not in the document]
Comment (JavaCafe01) [reply src/commands/poll.rs]: unwrap go brrr

**Comment by JavaCafe01** [comment]
@elkowar  Thanks for the review and feedback, its making me a better rust user (and a better programmer) :sunglasses:

File: src/commands/poll.rs [hunk 5]
```diff
@@ -37,9 +39,11 @@ pub async fn poll(ctx: &client::Context, msg: &Message, args: Args) -> CommandRe
...
-    let mut lines = args.rest().lines().collect_vec();
-    let title = lines.first().and_then(|line| line.strip_prefix("multi "));
+async fn poll_multi(ctx: &client::Context, msg: &Message) -> CommandResult {
+    let lines = msg.content.lines().collect_vec();
+    let title = lines.first().map(|line| line.split_at_word("multi").1);
+    let mut lines = lines.clone();
+
     if !lines.is_empty() {
         lines.remove(0);
     }
```
Comment (elkowar) [inline src/commands/poll.rs:49]: Just realized this could be a tiiiiiiny bit more efficient if we do the following:
```suggestion
    let mut lines_iter = msg.content.lines();
    let title = lines.next().map(|line|line.split_at_word("multi").1);
    let options_lines = lines_iter.collect_vec();
```
and then change the rest of the code to use `options_lines`, obviously. This saves a single clone and makes it a biiiiiiiiiit cleaner I'd say? not much tho.

How it works is that by doing `.next()` we advance the iterator by one element, giving us the first line as an Option. Then, when we collect, the first line will have already been consumed and won't be included in the vec, thus we have skipped it automatically, pretty much. Please test this before tho, I'm just writing it in github rn :kek:

File: src/extensions.rs [hunk 6]
```diff
@@ -195,4 +195,15 @@ impl<T: AsRef<str>> T {
...
     }
+
+    fn split_at_word<'a>(&'a self, split_at: &str) -> (String, String) {
+        let mut words = self.as_ref().trim().split(' ').collect_vec();
+        match words.iter().position(|w| w == &split_at) {
+            Some(word_ind) => {
+                let right_side = words.split_off(word_ind + 1).join(" ");
+                return (words.join(" "), right_side);
+            }
+            None => return (String::from(self.as_ref()), String::new()),
```
Comment (elkowar) [inline src/extensions.rs:206]: No need for returns here, as rust will just treat the last expression in any function (as long as it doesn't have a semicolon) as the return value. This means that here this is equivalent to doing `return match words.iter().etcetcetc` - which then again is equivalent to just doing the match without the `return` keyword, as it's implicitly getting returned bcos it's the last expression in the function, and doesn't have a semicolon.
```suggestion
            Some(word_ind) => {
                let right_side = words.split_off(word_ind + 1).join(" ");
                (words.join(" "), right_side)
            }
            None => (String::from(self.as_ref()), String::new()),
```

File: src/extensions.rs [hunk 7]
```diff
@@ -195,4 +195,15 @@ impl<T: AsRef<str>> T {
         let index = s.find(c)?;
         Some((&s[..index], &s[index + c.len_utf8()..]))
     }
+
+    fn split_at_word<'a>(&'a self, split_at: &str) -> (String, String) {
```
Comment (elkowar) [inline src/extensions.rs:199]: Could you add a short doc-comment here, explaining what the function does? specifically, providing one example of how it'd behaves  (use triple `///` for doc-comments)
i.e.:
```
Splits the string into two halves, separated by a given word.

## Example
`"foo bar baz".split_at_word("bar")  // ---> ("foo", "baz")`
```

I think in this case that's currently actually wrong, as currently the left side will be `foo bar`, right? That should prolly be fixed, see the next review (if i'm wrong plox ignore that one, i might be stupid rn, try it)

File: src/extensions.rs [hunk 8]
```diff
@@ -195,4 +195,15 @@ impl<T: AsRef<str>> T {
...
+        let mut words = self.as_ref().trim().split(' ').collect_vec();
+        match words.iter().position(|w| w == &split_at) {
+            Some(word_ind) => {
+                let right_side = words.split_off(word_ind + 1).join(" ");
```
Comment (elkowar) [inline src/extensions.rs:203]: This'll do the thing i mentioned above, where it will not include the word we are splitting by on any of the two sides, which I'd say is how i'd expect the function to behave
```suggestion
                let right_side = words.split_off(word_ind + 1).join(" ");
                words.pop();
```

**Comment by elkowar** [comment]
This is poggers! Thanks!
